
CREATE TABLE IF NOT EXISTS TB_ROLE(
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   role_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TB_USER(
   id BIGINT AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(255) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_USER_ROLE (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES TB_USER(id),
    FOREIGN KEY (role_id) REFERENCES TB_ROLE(id)
);

CREATE TABLE IF NOT EXISTS TB_PRODUCT(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_code VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    country VARCHAR(255) NOT NULL,
    creation_date TIMESTAMP NOT NULL
);